#! /usr/bin/env python3
from sys import argv


def factor():
    with open(argv[1]) as f:
        for n in f:
            num = int(n)
            fg = 0
            for i in range(2, int(num / 2) + 1, 1):
                if num % i == 0:
                    print("{:d}={}*{}".format(num, num // i, i))
                    fg = 1
                    break
            if fg == 0:
                print("{:d}={}*{}".format(num, num, 1))


if __name__ == "__main__":
    factor()
